# Generated by Django 5.1 on 2026-08-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_article_items',
            field=models.JSONField(blank=True, default=list, verbose_name='артикулы контракта'),
        ),
        migrations.AddField(
            model_name='contract',
            name='deadlines',
            field=models.JSONField(blank=True, default=list, verbose_name='дедлайны'),
        ),
        migrations.AddField(
            model_name='contract',
            name='delivery_schedule',
            field=models.JSONField(blank=True, default=list, verbose_name='график поставок по месяцам'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='cycle_start',
            field=models.DateField(blank=True, null=True, verbose_name='начало цикла'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='eff_pct',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8),
        ),
        migrations.AddField(
            model_name='schedule',
            name='graph_preset',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='пресет графика, напр. 2/2'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='rest_days',
            field=models.PositiveIntegerField(default=0, verbose_name='выходных в цикле'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='skip_weekends',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='staff_count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='schedule',
            name='work_days',
            field=models.PositiveIntegerField(default=0, verbose_name='рабочих дней в цикле'),
        ),
    ]
