# Generated by Django 5.1 on 2026-08-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_deliverybase_versioning'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualfrv',
            name='eff_pct',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8),
        ),
        migrations.AddField(
            model_name='manualfrv',
            name='frv_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='manualfrvsegment',
            name='absence',
            field=models.BooleanField(default=True, verbose_name='учитывать абсентеизм ×0.95'),
        ),
        migrations.AddField(
            model_name='manualfrvsegment',
            name='eff_pct',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8),
        ),
        migrations.AddField(
            model_name='manualfrvsegment',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='manualfrvsegment',
            name='people',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='manualfrvsegment',
            name='shift_min',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manualfrvsegment',
            name='work_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='schedulemonthoverride',
            name='eff_pct',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8),
        ),
        migrations.AddField(
            model_name='schedulemonthoverride',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='schedulemonthoverride',
            name='shift_time',
            field=models.PositiveIntegerField(default=480),
        ),
    ]
