# Generated by Django 5.1 on 2026-08-02 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_manualfrv_eff_pct_manualfrv_frv_min_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('username', models.CharField(blank=True, default='', max_length=150, verbose_name='логин на момент правки')),
                ('entity', models.CharField(max_length=64, verbose_name='что правили (путь API)')),
                ('src_id', models.BigIntegerField(blank=True, null=True, verbose_name='id записи в «Плане»')),
                ('row_id', models.BigIntegerField(blank=True, null=True, verbose_name='id записи в базе')),
                ('op_name', models.CharField(blank=True, default='', max_length=255, verbose_name='площадка записи')),
                ('action', models.CharField(max_length=16, verbose_name='create | update | delete')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='{поле: [было, стало]}')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='пояснение для массовых операций')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'изменение',
                'verbose_name_plural': 'журнал изменений',
                'ordering': ['-at', '-id'],
                'indexes': [models.Index(fields=['entity', 'src_id'], name='core_change_entity_c3ab7b_idx'), models.Index(fields=['op_name', 'at'], name='core_change_op_name_340d07_idx')],
            },
        ),
    ]
